### ISSUE TITLE
Content: add more concrete examples

### ISSUE THREAD

**Issue by luizaandrade** [bbdaniels/d4di#34]
I think because the idea is to be succinct, the text sometimes reads like it's trying to give a general, high-level description of something that is so abstract I don't understand what it's describing. I'd suggest being less general and adding concrete examples.

**Comment by luizaandrade** [comment]
- [ ] Though I understand what syntax and style mean, I don't understand what's being described in the lines below.
https://github.com/bbdaniels/d4di/blob/b9aae1636370e94a2738da1456533f6213e5a11a/manuscript/chapters/introduction.tex#L116

**Comment by bbdaniels** [comment]
Updated everything but the first one -- we should probably review Stata/code-related stuff separately if we get the style guide done. I will leave #35 open.
