### ISSUE TITLE
Content: transparency, replicability and credibility

### ISSUE THREAD

**Issue by luizaandrade** [bbdaniels/d4di#36]
Maybe good for us to discuss the argument behind this. It's definitely the main point, but how they are connected should be clearer in this paragraph. 

Here's how I see this: replicability is one key component of transparency. Transparency is necessary for consumers of research to be able to tell the quality of the research. Without it, all evidence credibility comes from reputation. And it's unclear what that reputation is based on, since it's not transparent.

So you do not maintain confidence in research in general by establishing the credibility of different pieces of evidence. Those pieces are credible because they are transparent, which (also) means they can be replicated. And though transparency does not _avoid_ serious errors, it increased the probability of identifying and correcting them.

https://github.com/bbdaniels/d4di/blob/de04e3d89cd4fcf7935a95dabe4b2048998adfc4/manuscript/chapters/handling-data.tex#L34

**Comment by kbjarkefur** [comment]
I like this logical way of describing it a lot:
> Here's how I see this: replicability is one key component of transparency. Transparency is necessary for consumers of research to be able to tell the quality of the research. Without it, all evidence credibility comes from reputation. And it's unclear what that reputation is based on, since it's not transparent.
