### ISSUE TITLE
Data collection: content

### ISSUE THREAD

**Issue by luizaandrade** [bbdaniels/d4di#47]
- [x] Make a point that you should always have an ID variable
- [x] Make a point that access to PII data should be restricted within the team to the people who will process it
- [ ] Add a paragraph on enumerator checks
- [x] Add a paragraph on tracking substitutions and attrition
- [x] Add tracking of main outcome variables to HFC
- [ ] Add a paragraph on de-identification
- [x] Rewrite [this](https://github.com/bbdaniels/d4di/blob/5a861ff1bd95714f6e0c893359c476e0df8af1c6/manuscript/chapters/data-collection.tex#L317) paragraph: it's unclear what "the combination of Dropbox and VeraCrypt" is. Make sure VeraCrypt was introduced, and if it wasn't, explain what it is. We should probably just say "encryption software", and cite VeraCrypt as an example. Also, I think we suggested other ways to deal with this, so I'm not sure why only this option is discussed in detail.

**Comment by bbdaniels** [comment]
Do we have any resources on enumerator checks? This is a really small portion of the Wiki page https://dimewiki.worldbank.org/wiki/Monitoring_Data_Quality

**Comment by bbdaniels** [comment]
I removed de-identification from this part already since it was redundant with the next section

**Comment by bbdaniels** [comment]
Done in 4c5e8daf2dc5305c21e195b23e1d64f2dce3b5f2
